modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"
[[mods]]
modId="hardernaturalhealing"
version="${file.jarVersion}"
displayName="Harder Natural Healing Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harder-spawners"
updateJSONURL="https://raw.githubusercontent.com/mactso/HarderNaturalHealing/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Harder Natural Healing Mod.'
[[dependencies.hardernaturalhealing]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.hardernaturalhealing]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18.0)"
    ordering="NONE"
    side="SERVER"
